export const SET_COMPANY = "SET_COMPANY"
export const SET_COMPANY_EVENT = "SET_COMPANY_EVENT"

export const AUTHENTICATE = "AUTHENTICATE"
export const DEAUTHENTICATE = "DEAUTHENTICATE"
export const RESTORE_AUTH_STATE = "RESTORE_AUTH_STATE"
