# Install MiniPC Software 
---
- name: Install RDSS Software
  hosts: all
  become: true
  vars_files:
    - ../vars.yaml
  tasks:  
  - name: Clean artifact path
    file:
      state: absent
      path: /tmp/rdss2
  - name: "Cloning RDSSv2 repo"
    git:
      repo: https://{{gitlabuser | urlencode}}:{{gitlabpassword | urlencode}}@gitlab.com/sigma-telecom/rdss.git
      dest: /tmp/rdss2
      # single_branch: yes
      version: change_ip
      accept_hostkey: yes
  - name: "Create installation directory"
    file:
      path: /opt/rdss
      state: directory
      mode: '0755'
