# Install MiniPC Software 
---
- name: Install RDSS Monitor
  hosts: all
  become: true
  vars_files:
    - ../vars.yaml
  tasks:
  - name: "Installing Monitor files"
    copy:
      remote_src: true
      src: "{{ temp_dir }}/monitor/src/"
      dest: "{{ base_dir }}/monitor"
  - name: "Remove unused monitor entrypoint file"
    file:
      path: "{{ base_dir }}/monitor/entrypoint.sh"
      state: absent
  - name: Apply Config Template
    template:
      src: monitor_config.j2
      dest: "{{ base_dir }}/monitor/config.py"
  - name: "Installing monitor system service"
    copy:
      remote_src: true
      src: "{{ temp_dir }}/monitor/monitorRDSS.service"
      dest: /etc/systemd/system
      owner: root
      group: root
  - name: "Start monitor"
    systemd:
      name: monitorRDSS
      state: restarted
      enabled: yes
