# Install MiniPC Software 
---
- name: Install RDSS Monitor
  hosts: all
  become: true
  tasks:
  - name: "Installing Monitor files"
    copy:
      remote_src: true
      src: /tmp/rdss2/monitor/src/
      dest: /opt/rdss/monitor
  - name: "Remove unused monitor entrypoint file"
    file:
      path: /opt/rdss/monitor/entrypoint.sh
      state: absent
  - name: "Installing monitor system service"
    copy:
      remote_src: true
      src: /tmp/rdss2/monitor/monitorRDSS.service
      dest: /etc/systemd/system
      owner: root
      group: root
    # notify:
    # - "Start monitor"
  - name: "Start monitor"
    systemd:
      name: monitorRDSS
      state: started
      enabled: yes
