# Install MiniPC Software 
---
- name: Install RDSS Frontend
  hosts: all
  become: true
  tasks:
  - name: "Installing frontend files"
    copy:
      remote_src: true
      src: /tmp/rdss2/frontend/src/
      dest: /opt/rdss/frontend
  - name: "Installing dependencies"
    shell: npm install
    args:
      chdir: /opt/rdss/frontend
  - name: "Patching hammerJS"
    copy:
      remote_src: true
      src: /tmp/rdss2/frontend/src/lib/hammer.js
      dest: /opt/rdss/frontend/node_modules/hammerjs/hammer.js
      owner: root
      group: root
  - name: "Build frontend dist"
    shell: npm run build
    args:
      chdir: /opt/rdss/frontend
  - name: "Installing frontend system service"
    copy:
      remote_src: true
      src: /tmp/rdss2/frontend/webappRDSS.service
      dest: /etc/systemd/system
      owner: root
      group: root
    # notify:
    # - "Start frontend"
  - name: "Start frontend"
    systemd:
      name: webappRDSS
      state: started
      enabled: yes
