# Install MiniPC Software 
---
- name: Install Debian Image Dependencies   
  hosts: icinga_master
  become: true
  roles:
  - role: gantsign.oh-my-zsh
    users:
      - username: sigmadev
      - username: root
  vars_files:
    - ../vars.yaml
