# Install MiniPC Software 
---
- name: Install Monitor Python Dependencies
  hosts: all
  become: true
  vars_files:
    - ../vars.yaml
  tasks:
  - name: "Install pip"
    apt:
      update_cache: yes
      name: python3-pip
      state: present
  - name: Install Monitor python packages
    pip:
      name:
        - python-socketio
        - pymongo
        - crccheck
        - pyserial
        - sympy
        - Flask
        - flask_socketio
        - eventlet
        - numpy

  - name: Dependencies
    apt:
        name:
            - htop
            - git
            - curl
            - zsh
            - vim
        state: present
    register: output

  - name: Add .vimrc template
    copy:
      src: "{{ temp_dir }}/custom/.vimrc"
      dest: /home/sigmadev/
      remote_src: yes
  - name: Add .vimrc template
    copy:
      src: "{{ temp_dir }}/custom/.vimrc"
      dest: /root/
      remote_src: yes

  - name: Install zsh-autosuggestions plugin for all users
    git:
      repo: "https://github.com/zsh-users/zsh-autosuggestions"
      dest: "/usr/share/oh-my-zsh/custom/plugins/zsh-autosuggestions"
      clone: yes
      version: master

  - name: Install zsh-syntax-highlighting plugin for all users
    git:
      repo: "https://github.com/zsh-users/zsh-syntax-highlighting"
      dest: "/usr/share/oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
      clone: yes
      version: master