export const SET_NAME = "SET_NAME"
export const SET_NAME_EVENT = "SET_NAME_EVENT"
export const SET_COMPANY = "SET_COMPANY"
export const SET_NAME_ROL = "SET_NAME_ROL"
export const SET_NAME_USER = "SET_NAME_USER"

export const SET_CONFIG = "SET_CONFIG"

export const SET_MONITOR_DATA_EVENT = "SET_MONITOR_DATA_EVENT"
export const SET_DIAGRAM_PATH = "SET_DIAGRAM_PATH"

export const SET_DEVICES = "SET_DEVICES"
export const SET_ACTIVE_COMPONENT = "SET_ACTIVE_COMPONENT"
